[env:uno]
platform = atmelavr @ 5.3.0
board = uno
framework = arduino
monitor_speed = 115200
upload_port = /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
monitor_port = /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
